name = "automated_trading_test_environment"
uuid = "acd55cec-8ad4-4058-8ce9-6d288b582186"
version = "0.1.0"
authors = ["sdwhardy <40562565+sdwhardy@users.noreply.github.com>"]

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GaussianMixtures = "cc18c42c-b769-54ff-9e2a-b28141a64aae"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Indicators = "70c4c096-89a6-5ec6-8236-da8aa3bd86fd"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MarketData = "945b72a4-3b13-509d-9b46-1525bb5c06de"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
Base64 = "1.11.0"
CSV = "0.10.15"
Clustering = "0.15.8"
DataFrames = "1.8.1"
Dates = "1.11.0"
Distributions = "0.25.122"
GaussianMixtures = "0.3.13"
HTTP = "0.9.17"
Indicators = "0.8.2"
JSON = "0.21.4"
JSON3 = "1.14.3"
LinearAlgebra = "1.12.0"
MarketData = "0.15.0"
MbedTLS = "1.1.9"
MultivariateStats = "0.10.3"
PlotlyJS = "0.18.17"
Plots = "1.41.2"
Printf = "1.11.0"
Random = "1.11.0"
SHA = "0.7.0"
Statistics = "1.11.1"
StatsBase = "0.34.9"
TimeSeries = "0.24.2"
TimeZones = "1.22.1"
