name = "automated_trading_test_environment"
uuid = "acd55cec-8ad4-4058-8ce9-6d288b582186"
version = "0.1.0"
authors = ["sdwhardy <40562565+sdwhardy@users.noreply.github.com>"]

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Indicators = "70c4c096-89a6-5ec6-8236-da8aa3bd86fd"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MarketData = "945b72a4-3b13-509d-9b46-1525bb5c06de"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
Base64 = "1.11.0"
CSV = "0.10.15"
DataFrames = "1.8.1"
Dates = "1.11.0"
HTTP = "0.9.17"
Indicators = "0.8.2"
JSON = "0.21.4"
JSON3 = "1.14.3"
MarketData = "0.15.0"
MbedTLS = "1.1.9"
SHA = "0.7.0"
TimeSeries = "0.24.2"
TimeZones = "1.22.1"
